name: Release BALL!

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set VERSION from tag
      run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build binary
      run: |
        mkdir -p dist/
        GOOS=linux GOARCH=amd64 go build -o dist/BallGame-${VERSION}-linux cmd/game.go
        GOOS=windows GOARCH=amd64 go build -o dist/BallGame-${VERSION}.exe cmd/game.go

    - name: Release 
      uses: softprops/action-gh-release@v2
      with:
        name: "Release ${{ VERSION }}"
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}